import { CalendarEvent, EventCategoryFilter } from '@/types';

export const eventCategoryFilters: EventCategoryFilter[] = [
  { id: 'all', label: '전체', emoji: '📅' },
  { id: 'institution', label: '경제지표', emoji: '🏛️' },
  { id: 'earnings', label: '실적발표', emoji: '📊' },
  { id: 'corporate', label: '기업이벤트', emoji: '🎉' },
  { id: 'crypto', label: '암호화폐', emoji: '🪙' },
];

export const calendarEvents: CalendarEvent[] = [
  // ========== 1월 ==========
  {
    id: 'bok-jan-2024',
    date: '2024-01-11',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 3.50% 동결',
  },
  {
    id: 'samsung-s24-unpacked',
    date: '2024-01-17',
    title: '삼성전자 갤럭시 S24 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy S24 시리즈 공개',
  },
  {
    id: 'tsla-4q-2023',
    date: '2024-01-24',
    title: 'Tesla 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'skhynix-4q-2023',
    date: '2024-01-25',
    title: 'SK하이닉스 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'msft-2q-2024',
    date: '2024-01-30',
    title: 'Microsoft 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'googl-4q-2023',
    date: '2024-01-30',
    title: 'Alphabet 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'aapl-1q-2024',
    date: '2024-01-30',
    title: 'Apple 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'fomc-jan-2024',
    date: '2024-01-31',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'samsung-4q-2023',
    date: '2024-01-31',
    title: '삼성전자 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2023년 4분기 실적 발표',
  },

  // ========== 2월 ==========
  {
    id: 'amzn-4q-2023',
    date: '2024-02-01',
    title: 'Amazon 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'naver-4q-2023',
    date: '2024-02-01',
    title: '네이버 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'kakao-4q-2023',
    date: '2024-02-08',
    title: '카카오 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'us-cpi-feb-2024',
    date: '2024-02-13',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 소비자물가지수',
  },
  {
    id: 'nvda-4q-2023',
    date: '2024-02-21',
    title: 'NVIDIA 4Q23 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'bok-feb-2024',
    date: '2024-02-22',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 3.50% 동결',
  },

  // ========== 3월 ==========
  {
    id: 'eth-dencun',
    date: '2024-03-13',
    title: '이더리움 덴쿤 업그레이드',
    category: 'crypto',
    companyDomain: 'ethereum.org',
    importance: 'high',
    description: 'Proto-danksharding 도입',
  },
  {
    id: 'fomc-mar-2024',
    date: '2024-03-20',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },

  // ========== 4월 ==========
  {
    id: 'bok-apr-2024',
    date: '2024-04-12',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 3.50% 동결',
  },
  {
    id: 'tsla-1q-2024',
    date: '2024-04-17',
    title: 'Tesla 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'btc-halving',
    date: '2024-04-19',
    title: '비트코인 반감기',
    category: 'crypto',
    companyDomain: 'bitcoin.org',
    importance: 'high',
    time: '04:00',
    description: '채굴 보상 6.25 → 3.125 BTC로 감소',
  },
  {
    id: 'googl-1q-2024',
    date: '2024-04-25',
    title: 'Alphabet 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'msft-3q-2024',
    date: '2024-04-25',
    title: 'Microsoft 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'skhynix-1q-2024',
    date: '2024-04-25',
    title: 'SK하이닉스 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'naver-1q-2024',
    date: '2024-04-25',
    title: '네이버 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'samsung-1q-2024',
    date: '2024-04-30',
    title: '삼성전자 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'amzn-1q-2024',
    date: '2024-04-30',
    title: 'Amazon 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },

  // ========== 5월 ==========
  {
    id: 'fomc-may-2024',
    date: '2024-05-01',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'aapl-2q-2024',
    date: '2024-05-02',
    title: 'Apple 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'kakao-1q-2024',
    date: '2024-05-09',
    title: '카카오 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'nvda-1q-2024',
    date: '2024-05-22',
    title: 'NVIDIA 1Q24 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'bok-may-2024',
    date: '2024-05-23',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 3.50% 동결',
  },

  // ========== 6월 ==========
  {
    id: 'apple-wwdc-2024',
    date: '2024-06-10',
    title: 'Apple WWDC 2024',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'Apple 개발자 컨퍼런스, Apple Intelligence 발표',
  },
  {
    id: 'fomc-jun-2024',
    date: '2024-06-12',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },

  // ========== 7월 ==========
  {
    id: 'samsung-unpacked-jul-2024',
    date: '2024-07-10',
    title: '삼성전자 갤럭시 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy Z Fold6, Z Flip6 공개',
  },
  {
    id: 'bok-jul-2024',
    date: '2024-07-11',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 3.50% 동결',
  },
  {
    id: 'tsla-2q-2024',
    date: '2024-07-23',
    title: 'Tesla 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'googl-2q-2024',
    date: '2024-07-23',
    title: 'Alphabet 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'skhynix-2q-2024',
    date: '2024-07-25',
    title: 'SK하이닉스 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'naver-2q-2024',
    date: '2024-07-25',
    title: '네이버 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'msft-4q-2024',
    date: '2024-07-30',
    title: 'Microsoft 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'fomc-jul-2024',
    date: '2024-07-31',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'samsung-2q-2024',
    date: '2024-07-31',
    title: '삼성전자 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 2분기 실적 발표',
  },

  // ========== 8월 ==========
  {
    id: 'aapl-3q-2024',
    date: '2024-08-01',
    title: 'Apple 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'amzn-2q-2024',
    date: '2024-08-01',
    title: 'Amazon 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'kakao-2q-2024',
    date: '2024-08-08',
    title: '카카오 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'bok-aug-2024',
    date: '2024-08-22',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 3.50% 동결',
  },
  {
    id: 'nvda-2q-2024',
    date: '2024-08-28',
    title: 'NVIDIA 2Q24 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },

  // ========== 9월 ==========
  {
    id: 'apple-iphone16-event',
    date: '2024-09-09',
    title: 'Apple 아이폰 16 이벤트',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'iPhone 16 시리즈 공개',
  },
  {
    id: 'fomc-sep-2024',
    date: '2024-09-18',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 50bp 인하 (5.00%)',
  },

  // ========== 10월 ==========
  {
    id: 'bok-oct-2024',
    date: '2024-10-11',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 25bp 인하 (3.25%)',
  },
  {
    id: 'tsla-3q-2024',
    date: '2024-10-23',
    title: 'Tesla 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'skhynix-3q-2024',
    date: '2024-10-24',
    title: 'SK하이닉스 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'naver-3q-2024',
    date: '2024-10-24',
    title: '네이버 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'googl-3q-2024',
    date: '2024-10-29',
    title: 'Alphabet 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'aapl-4q-2024',
    date: '2024-10-30',
    title: 'Apple 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'msft-1q-2025',
    date: '2024-10-30',
    title: 'Microsoft 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'samsung-3q-2024',
    date: '2024-10-31',
    title: '삼성전자 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'amzn-3q-2024',
    date: '2024-10-31',
    title: 'Amazon 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },

  // ========== 11월 ==========
  {
    id: 'fomc-nov-2024',
    date: '2024-11-07',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 25bp 인하 (4.75%)',
  },
  {
    id: 'kakao-3q-2024',
    date: '2024-11-07',
    title: '카카오 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'nvda-3q-2024',
    date: '2024-11-20',
    title: 'NVIDIA 3Q24 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'bok-nov-2024',
    date: '2024-11-28',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 25bp 인하 (3.00%)',
  },

  // ========== 12월 ==========
  {
    id: 'fomc-dec-2024',
    date: '2024-12-18',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 25bp 인하 (4.50%)',
  },
];
