import { CalendarEvent, EventCategoryFilter } from '@/types';

export const eventCategoryFilters: EventCategoryFilter[] = [
  { id: 'all', label: '전체', emoji: '📅' },
  { id: 'institution', label: '경제지표', emoji: '🏛️' },
  { id: 'earnings', label: '실적발표', emoji: '📊' },
  { id: 'corporate', label: '기업이벤트', emoji: '🎉' },
  { id: 'crypto', label: '암호화폐', emoji: '🪙' },
];

export const calendarEvents: CalendarEvent[] = [
  // ╔════════════════════════════════════════════════════════════════════════════╗
  // ║                              2025년 이벤트                                  ║
  // ╚════════════════════════════════════════════════════════════════════════════╝

  // ==================== 2025년 1월 ====================
  // 경제지표
  {
    id: 'us-ism-jan-2025',
    date: '2025-01-03',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '12월 ISM 제조업 PMI',
  },
  {
    id: 'us-jobs-jan-2025',
    date: '2025-01-10',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '12월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-jan-2025',
    date: '2025-01-15',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '12월 소비자물가지수',
  },
  {
    id: 'bok-jan-2025',
    date: '2025-01-16',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'kr-cpi-jan-2025',
    date: '2025-01-07',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '12월 소비자물가지수',
  },
  {
    id: 'fomc-jan-2025',
    date: '2025-01-29',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-jan-2025',
    date: '2025-01-31',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '12월 개인소비지출 물가지수',
  },
  {
    id: 'us-gdp-q4-2024',
    date: '2025-01-30',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2024년 4분기 GDP 속보치',
  },

  // 기업이벤트
  {
    id: 'ces-2025',
    date: '2025-01-07',
    title: 'CES 2025',
    category: 'corporate',
    companyDomain: 'ces.tech',
    importance: 'high',
    time: '09:00',
    description: '세계 최대 가전·IT 박람회 개막',
  },
  {
    id: 'samsung-s25-unpacked',
    date: '2025-01-22',
    title: '삼성전자 갤럭시 S25 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy S25 시리즈 공개',
  },

  // 실적발표
  {
    id: 'tsla-4q-2024',
    date: '2025-01-29',
    title: 'Tesla 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'msft-2q-2025',
    date: '2025-01-29',
    title: 'Microsoft 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'meta-4q-2024',
    date: '2025-01-29',
    title: 'Meta 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'aapl-1q-2025',
    date: '2025-01-30',
    title: 'Apple 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'samsung-4q-2024',
    date: '2025-01-30',
    title: '삼성전자 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'skhynix-4q-2024',
    date: '2025-01-23',
    title: 'SK하이닉스 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 4분기 실적 발표',
  },

  // ==================== 2025년 2월 ====================
  // 경제지표
  {
    id: 'us-ism-feb-2025',
    date: '2025-02-03',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '1월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-feb-2025',
    date: '2025-02-04',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '1월 소비자물가지수',
  },
  {
    id: 'us-jobs-feb-2025',
    date: '2025-02-07',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-feb-2025',
    date: '2025-02-12',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 소비자물가지수',
  },
  {
    id: 'bok-feb-2025',
    date: '2025-02-27',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-feb-2025',
    date: '2025-02-28',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'mwc-2025',
    date: '2025-02-24',
    title: 'MWC 2025',
    category: 'corporate',
    companyDomain: 'mwcbarcelona.com',
    importance: 'high',
    time: '18:00',
    description: '모바일 월드 콩그레스 개막',
  },

  // 실적발표
  {
    id: 'googl-4q-2024',
    date: '2025-02-04',
    title: 'Alphabet 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'amzn-4q-2024',
    date: '2025-02-06',
    title: 'Amazon 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'naver-4q-2024',
    date: '2025-02-06',
    title: '네이버 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'kakao-4q-2024',
    date: '2025-02-13',
    title: '카카오 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'nvda-4q-2024',
    date: '2025-02-26',
    title: 'NVIDIA 4Q24 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },

  // ==================== 2025년 3월 ====================
  // 경제지표
  {
    id: 'us-ism-mar-2025',
    date: '2025-03-03',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '2월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-mar-2025',
    date: '2025-03-04',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '2월 소비자물가지수',
  },
  {
    id: 'us-jobs-mar-2025',
    date: '2025-03-07',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-mar-2025',
    date: '2025-03-12',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2월 소비자물가지수',
  },
  {
    id: 'fomc-mar-2025',
    date: '2025-03-19',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-mar-2025',
    date: '2025-03-28',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2월 개인소비지출 물가지수',
  },

  // 암호화폐
  {
    id: 'eth-pectra-2025',
    date: '2025-03-15',
    title: '이더리움 Pectra 업그레이드',
    category: 'crypto',
    companyDomain: 'ethereum.org',
    importance: 'high',
    description: 'EIP-7702 계정 추상화 포함',
  },

  // ==================== 2025년 4월 ====================
  // 경제지표
  {
    id: 'us-ism-apr-2025',
    date: '2025-04-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '3월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-apr-2025',
    date: '2025-04-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '3월 소비자물가지수',
  },
  {
    id: 'us-jobs-apr-2025',
    date: '2025-04-04',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '3월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-apr-2025',
    date: '2025-04-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '3월 소비자물가지수',
  },
  {
    id: 'bok-apr-2025',
    date: '2025-04-17',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-apr-2025',
    date: '2025-04-25',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '3월 개인소비지출 물가지수',
  },
  {
    id: 'us-gdp-q1-2025',
    date: '2025-04-30',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2025년 1분기 GDP 속보치',
  },

  // 실적발표
  {
    id: 'tsla-1q-2025',
    date: '2025-04-23',
    title: 'Tesla 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'googl-1q-2025',
    date: '2025-04-24',
    title: 'Alphabet 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'msft-3q-2025',
    date: '2025-04-24',
    title: 'Microsoft 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'meta-1q-2025',
    date: '2025-04-30',
    title: 'Meta 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'skhynix-1q-2025',
    date: '2025-04-24',
    title: 'SK하이닉스 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'naver-1q-2025',
    date: '2025-04-24',
    title: '네이버 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'samsung-1q-2025',
    date: '2025-04-30',
    title: '삼성전자 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 1분기 실적 발표',
  },

  // ==================== 2025년 5월 ====================
  // 경제지표
  {
    id: 'us-ism-may-2025',
    date: '2025-05-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '4월 ISM 제조업 PMI',
  },
  {
    id: 'aapl-2q-2025',
    date: '2025-05-01',
    title: 'Apple 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'amzn-1q-2025',
    date: '2025-05-01',
    title: 'Amazon 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'kr-cpi-may-2025',
    date: '2025-05-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '4월 소비자물가지수',
  },
  {
    id: 'us-jobs-may-2025',
    date: '2025-05-02',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '4월 비농업고용 및 실업률',
  },
  {
    id: 'fomc-may-2025',
    date: '2025-05-07',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'kakao-1q-2025',
    date: '2025-05-08',
    title: '카카오 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'us-cpi-may-2025',
    date: '2025-05-13',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '4월 소비자물가지수',
  },
  {
    id: 'nvda-1q-2025',
    date: '2025-05-28',
    title: 'NVIDIA 1Q25 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 1분기 실적 발표',
  },
  {
    id: 'bok-may-2025',
    date: '2025-05-29',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-may-2025',
    date: '2025-05-30',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '4월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'google-io-2025',
    date: '2025-05-14',
    title: 'Google I/O 2025',
    category: 'corporate',
    companyDomain: 'google.com',
    importance: 'high',
    time: '02:00',
    description: 'Google 개발자 컨퍼런스',
  },

  // ==================== 2025년 6월 ====================
  // 경제지표
  {
    id: 'us-ism-jun-2025',
    date: '2025-06-02',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '5월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-jun-2025',
    date: '2025-06-03',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '5월 소비자물가지수',
  },
  {
    id: 'us-jobs-jun-2025',
    date: '2025-06-06',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '5월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-jun-2025',
    date: '2025-06-11',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '5월 소비자물가지수',
  },
  {
    id: 'fomc-jun-2025',
    date: '2025-06-18',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-jun-2025',
    date: '2025-06-27',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '5월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'apple-wwdc-2025',
    date: '2025-06-09',
    title: 'Apple WWDC 2025',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'Apple 개발자 컨퍼런스',
  },

  // ==================== 2025년 7월 ====================
  // 경제지표
  {
    id: 'us-ism-jul-2025',
    date: '2025-07-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '6월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-jul-2025',
    date: '2025-07-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '6월 소비자물가지수',
  },
  {
    id: 'us-jobs-jul-2025',
    date: '2025-07-03',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '6월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-jul-2025',
    date: '2025-07-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '6월 소비자물가지수',
  },
  {
    id: 'bok-jul-2025',
    date: '2025-07-17',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-jul-2025',
    date: '2025-07-25',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '6월 개인소비지출 물가지수',
  },
  {
    id: 'us-gdp-q2-2025',
    date: '2025-07-30',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2025년 2분기 GDP 속보치',
  },
  {
    id: 'fomc-jul-2025',
    date: '2025-07-30',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },

  // 기업이벤트
  {
    id: 'samsung-unpacked-jul-2025',
    date: '2025-07-09',
    title: '삼성전자 갤럭시 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy Z Fold7, Z Flip7 공개',
  },

  // 실적발표
  {
    id: 'tsla-2q-2025',
    date: '2025-07-23',
    title: 'Tesla 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'googl-2q-2025',
    date: '2025-07-24',
    title: 'Alphabet 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'msft-4q-2025',
    date: '2025-07-24',
    title: 'Microsoft 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'skhynix-2q-2025',
    date: '2025-07-24',
    title: 'SK하이닉스 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'naver-2q-2025',
    date: '2025-07-24',
    title: '네이버 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'meta-2q-2025',
    date: '2025-07-30',
    title: 'Meta 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'samsung-2q-2025',
    date: '2025-07-31',
    title: '삼성전자 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 2분기 실적 발표',
  },

  // ==================== 2025년 8월 ====================
  // 경제지표
  {
    id: 'us-ism-aug-2025',
    date: '2025-08-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '7월 ISM 제조업 PMI',
  },
  {
    id: 'aapl-3q-2025',
    date: '2025-07-31',
    title: 'Apple 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'amzn-2q-2025',
    date: '2025-07-31',
    title: 'Amazon 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'kr-cpi-aug-2025',
    date: '2025-08-05',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '7월 소비자물가지수',
  },
  {
    id: 'kakao-2q-2025',
    date: '2025-08-07',
    title: '카카오 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'us-jobs-aug-2025',
    date: '2025-08-01',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '7월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-aug-2025',
    date: '2025-08-13',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '7월 소비자물가지수',
  },
  {
    id: 'bok-aug-2025',
    date: '2025-08-28',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'nvda-2q-2025',
    date: '2025-08-27',
    title: 'NVIDIA 2Q25 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 2분기 실적 발표',
  },
  {
    id: 'us-pce-aug-2025',
    date: '2025-08-29',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '7월 개인소비지출 물가지수',
  },

  // ==================== 2025년 9월 ====================
  // 경제지표
  {
    id: 'us-ism-sep-2025',
    date: '2025-09-02',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '8월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-sep-2025',
    date: '2025-09-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '8월 소비자물가지수',
  },
  {
    id: 'us-jobs-sep-2025',
    date: '2025-09-05',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '8월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-sep-2025',
    date: '2025-09-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '8월 소비자물가지수',
  },
  {
    id: 'fomc-sep-2025',
    date: '2025-09-17',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-sep-2025',
    date: '2025-09-26',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '8월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'apple-iphone17-event',
    date: '2025-09-09',
    title: 'Apple 아이폰 17 이벤트',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'iPhone 17 시리즈 공개 예상',
  },

  // ==================== 2025년 10월 ====================
  // 경제지표
  {
    id: 'us-ism-oct-2025',
    date: '2025-10-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '9월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-oct-2025',
    date: '2025-10-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '9월 소비자물가지수',
  },
  {
    id: 'us-jobs-oct-2025',
    date: '2025-10-03',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '9월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-oct-2025',
    date: '2025-10-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '9월 소비자물가지수',
  },
  {
    id: 'bok-oct-2025',
    date: '2025-10-16',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-oct-2025',
    date: '2025-10-31',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '9월 개인소비지출 물가지수',
  },
  {
    id: 'us-gdp-q3-2025',
    date: '2025-10-30',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2025년 3분기 GDP 속보치',
  },

  // 실적발표
  {
    id: 'tsla-3q-2025',
    date: '2025-10-22',
    title: 'Tesla 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'skhynix-3q-2025',
    date: '2025-10-23',
    title: 'SK하이닉스 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'naver-3q-2025',
    date: '2025-10-23',
    title: '네이버 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'googl-3q-2025',
    date: '2025-10-28',
    title: 'Alphabet 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'msft-1q-2026',
    date: '2025-10-28',
    title: 'Microsoft 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'meta-3q-2025',
    date: '2025-10-29',
    title: 'Meta 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'aapl-4q-2025',
    date: '2025-10-30',
    title: 'Apple 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'amzn-3q-2025',
    date: '2025-10-30',
    title: 'Amazon 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'samsung-3q-2025',
    date: '2025-10-31',
    title: '삼성전자 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 3분기 실적 발표',
  },

  // ==================== 2025년 11월 ====================
  // 경제지표
  {
    id: 'us-ism-nov-2025',
    date: '2025-11-03',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '10월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-nov-2025',
    date: '2025-11-04',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '10월 소비자물가지수',
  },
  {
    id: 'fomc-nov-2025',
    date: '2025-11-05',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'kakao-3q-2025',
    date: '2025-11-06',
    title: '카카오 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'us-jobs-nov-2025',
    date: '2025-11-07',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '10월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-nov-2025',
    date: '2025-11-12',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '10월 소비자물가지수',
  },
  {
    id: 'nvda-3q-2025',
    date: '2025-11-19',
    title: 'NVIDIA 3Q25 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 3분기 실적 발표',
  },
  {
    id: 'bok-nov-2025',
    date: '2025-11-27',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-nov-2025',
    date: '2025-11-28',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '10월 개인소비지출 물가지수',
  },

  // ==================== 2025년 12월 ====================
  // 경제지표
  {
    id: 'us-ism-dec-2025',
    date: '2025-12-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '11월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-dec-2025',
    date: '2025-12-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '11월 소비자물가지수',
  },
  {
    id: 'us-jobs-dec-2025',
    date: '2025-12-05',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '11월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-dec-2025',
    date: '2025-12-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '11월 소비자물가지수',
  },
  {
    id: 'fomc-dec-2025',
    date: '2025-12-17',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-dec-2025',
    date: '2025-12-19',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '11월 개인소비지출 물가지수',
  },

  // ╔════════════════════════════════════════════════════════════════════════════╗
  // ║                              2026년 이벤트                                  ║
  // ╚════════════════════════════════════════════════════════════════════════════╝

  // ==================== 2026년 1월 ====================
  // 경제지표
  {
    id: 'us-ism-jan-2026',
    date: '2026-01-02',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '12월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-jan-2026',
    date: '2026-01-06',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '12월 소비자물가지수',
  },
  {
    id: 'us-jobs-jan-2026',
    date: '2026-01-09',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '12월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-jan-2026',
    date: '2026-01-14',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '12월 소비자물가지수',
  },
  {
    id: 'bok-jan-2026',
    date: '2026-01-15',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'fomc-jan-2026',
    date: '2026-01-28',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-gdp-q4-2025',
    date: '2026-01-29',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2025년 4분기 GDP 속보치',
  },
  {
    id: 'us-pce-jan-2026',
    date: '2026-01-30',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '12월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'ces-2026',
    date: '2026-01-06',
    title: 'CES 2026',
    category: 'corporate',
    companyDomain: 'ces.tech',
    importance: 'high',
    time: '09:00',
    description: '세계 최대 가전·IT 박람회 개막',
  },
  {
    id: 'samsung-s26-unpacked',
    date: '2026-01-21',
    title: '삼성전자 갤럭시 S26 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy S26 시리즈 공개 예상',
  },

  // 실적발표
  {
    id: 'skhynix-4q-2025',
    date: '2026-01-22',
    title: 'SK하이닉스 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'tsla-4q-2025',
    date: '2026-01-28',
    title: 'Tesla 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'msft-2q-2026',
    date: '2026-01-29',
    title: 'Microsoft 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'meta-4q-2025',
    date: '2026-01-29',
    title: 'Meta 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'aapl-1q-2026',
    date: '2026-01-30',
    title: 'Apple 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'samsung-4q-2025',
    date: '2026-01-30',
    title: '삼성전자 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2025년 4분기 실적 발표',
  },

  // ==================== 2026년 2월 ====================
  // 경제지표
  {
    id: 'us-ism-feb-2026',
    date: '2026-02-02',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '1월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-feb-2026',
    date: '2026-02-03',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '1월 소비자물가지수',
  },
  {
    id: 'us-jobs-feb-2026',
    date: '2026-02-06',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-feb-2026',
    date: '2026-02-11',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 소비자물가지수',
  },
  {
    id: 'bok-feb-2026',
    date: '2026-02-26',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-feb-2026',
    date: '2026-02-27',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'mwc-2026',
    date: '2026-02-23',
    title: 'MWC 2026',
    category: 'corporate',
    companyDomain: 'mwcbarcelona.com',
    importance: 'high',
    time: '18:00',
    description: '모바일 월드 콩그레스 개막',
  },

  // 실적발표
  {
    id: 'googl-4q-2025',
    date: '2026-02-03',
    title: 'Alphabet 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'amzn-4q-2025',
    date: '2026-02-05',
    title: 'Amazon 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'naver-4q-2025',
    date: '2026-02-05',
    title: '네이버 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'kakao-4q-2025',
    date: '2026-02-12',
    title: '카카오 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2025년 4분기 실적 발표',
  },
  {
    id: 'nvda-4q-2025',
    date: '2026-02-25',
    title: 'NVIDIA 4Q25 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2025년 4분기 실적 발표',
  },

  // ==================== 2026년 3월 ====================
  // 경제지표
  {
    id: 'us-ism-mar-2026',
    date: '2026-03-02',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '2월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-mar-2026',
    date: '2026-03-03',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '2월 소비자물가지수',
  },
  {
    id: 'us-jobs-mar-2026',
    date: '2026-03-06',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-mar-2026',
    date: '2026-03-11',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2월 소비자물가지수',
  },
  {
    id: 'fomc-mar-2026',
    date: '2026-03-18',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-mar-2026',
    date: '2026-03-27',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2월 개인소비지출 물가지수',
  },

  // ==================== 2026년 4월 ====================
  // 경제지표
  {
    id: 'us-ism-apr-2026',
    date: '2026-04-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '3월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-apr-2026',
    date: '2026-04-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '3월 소비자물가지수',
  },
  {
    id: 'us-jobs-apr-2026',
    date: '2026-04-03',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '3월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-apr-2026',
    date: '2026-04-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '3월 소비자물가지수',
  },
  {
    id: 'bok-apr-2026',
    date: '2026-04-16',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-apr-2026',
    date: '2026-04-24',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '3월 개인소비지출 물가지수',
  },
  {
    id: 'us-gdp-q1-2026',
    date: '2026-04-29',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2026년 1분기 GDP 속보치',
  },

  // 실적발표
  {
    id: 'tsla-1q-2026',
    date: '2026-04-22',
    title: 'Tesla 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'googl-1q-2026',
    date: '2026-04-23',
    title: 'Alphabet 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'msft-3q-2026',
    date: '2026-04-23',
    title: 'Microsoft 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'skhynix-1q-2026',
    date: '2026-04-23',
    title: 'SK하이닉스 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'naver-1q-2026',
    date: '2026-04-23',
    title: '네이버 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'meta-1q-2026',
    date: '2026-04-29',
    title: 'Meta 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'samsung-1q-2026',
    date: '2026-04-30',
    title: '삼성전자 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2026년 1분기 실적 발표',
  },

  // ==================== 2026년 5월 ====================
  // 경제지표
  {
    id: 'us-ism-may-2026',
    date: '2026-05-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '4월 ISM 제조업 PMI',
  },
  {
    id: 'aapl-2q-2026',
    date: '2026-04-30',
    title: 'Apple 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'amzn-1q-2026',
    date: '2026-04-30',
    title: 'Amazon 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'kr-cpi-may-2026',
    date: '2026-05-05',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '4월 소비자물가지수',
  },
  {
    id: 'fomc-may-2026',
    date: '2026-05-06',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'kakao-1q-2026',
    date: '2026-05-07',
    title: '카카오 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'us-jobs-may-2026',
    date: '2026-05-08',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '4월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-may-2026',
    date: '2026-05-12',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '4월 소비자물가지수',
  },
  {
    id: 'nvda-1q-2026',
    date: '2026-05-27',
    title: 'NVIDIA 1Q26 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 1분기 실적 발표',
  },
  {
    id: 'bok-may-2026',
    date: '2026-05-28',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-may-2026',
    date: '2026-05-29',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '4월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'google-io-2026',
    date: '2026-05-13',
    title: 'Google I/O 2026',
    category: 'corporate',
    companyDomain: 'google.com',
    importance: 'high',
    time: '02:00',
    description: 'Google 개발자 컨퍼런스',
  },

  // ==================== 2026년 6월 ====================
  // 경제지표
  {
    id: 'us-ism-jun-2026',
    date: '2026-06-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '5월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-jun-2026',
    date: '2026-06-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '5월 소비자물가지수',
  },
  {
    id: 'us-jobs-jun-2026',
    date: '2026-06-05',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '5월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-jun-2026',
    date: '2026-06-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '5월 소비자물가지수',
  },
  {
    id: 'fomc-jun-2026',
    date: '2026-06-17',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-jun-2026',
    date: '2026-06-26',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '5월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'apple-wwdc-2026',
    date: '2026-06-08',
    title: 'Apple WWDC 2026',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'Apple 개발자 컨퍼런스',
  },

  // ==================== 2026년 7월 ====================
  // 경제지표
  {
    id: 'us-ism-jul-2026',
    date: '2026-07-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '6월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-jul-2026',
    date: '2026-07-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '6월 소비자물가지수',
  },
  {
    id: 'us-jobs-jul-2026',
    date: '2026-07-02',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '6월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-jul-2026',
    date: '2026-07-14',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '6월 소비자물가지수',
  },
  {
    id: 'bok-jul-2026',
    date: '2026-07-16',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-jul-2026',
    date: '2026-07-24',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '6월 개인소비지출 물가지수',
  },
  {
    id: 'fomc-jul-2026',
    date: '2026-07-29',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-gdp-q2-2026',
    date: '2026-07-30',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2026년 2분기 GDP 속보치',
  },

  // 기업이벤트
  {
    id: 'samsung-unpacked-jul-2026',
    date: '2026-07-08',
    title: '삼성전자 갤럭시 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy Z 시리즈 공개 예상',
  },

  // 실적발표
  {
    id: 'tsla-2q-2026',
    date: '2026-07-22',
    title: 'Tesla 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'googl-2q-2026',
    date: '2026-07-23',
    title: 'Alphabet 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'msft-4q-2026',
    date: '2026-07-23',
    title: 'Microsoft 4Q26 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 4분기 실적 발표',
  },
  {
    id: 'skhynix-2q-2026',
    date: '2026-07-23',
    title: 'SK하이닉스 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'naver-2q-2026',
    date: '2026-07-23',
    title: '네이버 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'meta-2q-2026',
    date: '2026-07-29',
    title: 'Meta 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'aapl-3q-2026',
    date: '2026-07-30',
    title: 'Apple 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'amzn-2q-2026',
    date: '2026-07-30',
    title: 'Amazon 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'samsung-2q-2026',
    date: '2026-07-31',
    title: '삼성전자 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2026년 2분기 실적 발표',
  },

  // ==================== 2026년 8월 ====================
  // 경제지표
  {
    id: 'us-ism-aug-2026',
    date: '2026-08-03',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '7월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-aug-2026',
    date: '2026-08-04',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '7월 소비자물가지수',
  },
  {
    id: 'kakao-2q-2026',
    date: '2026-08-06',
    title: '카카오 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'us-jobs-aug-2026',
    date: '2026-08-07',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '7월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-aug-2026',
    date: '2026-08-12',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '7월 소비자물가지수',
  },
  {
    id: 'nvda-2q-2026',
    date: '2026-08-26',
    title: 'NVIDIA 2Q26 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 2분기 실적 발표',
  },
  {
    id: 'bok-aug-2026',
    date: '2026-08-27',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-aug-2026',
    date: '2026-08-28',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '7월 개인소비지출 물가지수',
  },

  // ==================== 2026년 9월 ====================
  // 경제지표
  {
    id: 'us-ism-sep-2026',
    date: '2026-09-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '8월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-sep-2026',
    date: '2026-09-01',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '8월 소비자물가지수',
  },
  {
    id: 'us-jobs-sep-2026',
    date: '2026-09-04',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '8월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-sep-2026',
    date: '2026-09-11',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '8월 소비자물가지수',
  },
  {
    id: 'fomc-sep-2026',
    date: '2026-09-16',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-sep-2026',
    date: '2026-09-25',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '8월 개인소비지출 물가지수',
  },

  // 기업이벤트
  {
    id: 'apple-iphone18-event',
    date: '2026-09-08',
    title: 'Apple 아이폰 18 이벤트',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'iPhone 18 시리즈 공개 예상',
  },

  // ==================== 2026년 10월 ====================
  // 경제지표
  {
    id: 'us-ism-oct-2026',
    date: '2026-10-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '9월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-oct-2026',
    date: '2026-10-02',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '9월 소비자물가지수',
  },
  {
    id: 'us-jobs-oct-2026',
    date: '2026-10-02',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '9월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-oct-2026',
    date: '2026-10-13',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '9월 소비자물가지수',
  },
  {
    id: 'bok-oct-2026',
    date: '2026-10-15',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-oct-2026',
    date: '2026-10-30',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '9월 개인소비지출 물가지수',
  },
  {
    id: 'us-gdp-q3-2026',
    date: '2026-10-29',
    title: '미국 GDP 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '2026년 3분기 GDP 속보치',
  },

  // 실적발표
  {
    id: 'tsla-3q-2026',
    date: '2026-10-21',
    title: 'Tesla 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'skhynix-3q-2026',
    date: '2026-10-22',
    title: 'SK하이닉스 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'skhynix.com',
    importance: 'high',
    time: '09:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'naver-3q-2026',
    date: '2026-10-22',
    title: '네이버 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'naver.com',
    importance: 'high',
    time: '16:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'googl-3q-2026',
    date: '2026-10-27',
    title: 'Alphabet 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'google.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'msft-1q-2027',
    date: '2026-10-27',
    title: 'Microsoft 1Q27 실적발표',
    category: 'earnings',
    companyDomain: 'microsoft.com',
    importance: 'high',
    time: '06:00',
    description: '2027년 1분기 실적 발표',
  },
  {
    id: 'meta-3q-2026',
    date: '2026-10-28',
    title: 'Meta 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'meta.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'aapl-4q-2026',
    date: '2026-10-29',
    title: 'Apple 4Q26 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 4분기 실적 발표',
  },
  {
    id: 'amzn-3q-2026',
    date: '2026-10-29',
    title: 'Amazon 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'amazon.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'samsung-3q-2026',
    date: '2026-10-30',
    title: '삼성전자 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2026년 3분기 실적 발표',
  },

  // ==================== 2026년 11월 ====================
  // 경제지표
  {
    id: 'us-ism-nov-2026',
    date: '2026-11-02',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '10월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-nov-2026',
    date: '2026-11-03',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '10월 소비자물가지수',
  },
  {
    id: 'fomc-nov-2026',
    date: '2026-11-04',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'kakao-3q-2026',
    date: '2026-11-05',
    title: '카카오 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'kakaocorp.com',
    importance: 'high',
    time: '16:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'us-jobs-nov-2026',
    date: '2026-11-06',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '10월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-nov-2026',
    date: '2026-11-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '10월 소비자물가지수',
  },
  {
    id: 'nvda-3q-2026',
    date: '2026-11-18',
    title: 'NVIDIA 3Q26 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2026년 3분기 실적 발표',
  },
  {
    id: 'bok-nov-2026',
    date: '2026-11-26',
    title: '한국은행 금리결정',
    category: 'institution',
    countryCode: 'kr',
    importance: 'high',
    time: '10:00',
    description: '기준금리 결정',
  },
  {
    id: 'us-pce-nov-2026',
    date: '2026-11-27',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '10월 개인소비지출 물가지수',
  },

  // ==================== 2026년 12월 ====================
  // 경제지표
  {
    id: 'us-ism-dec-2026',
    date: '2026-12-01',
    title: '미국 ISM 제조업지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'medium',
    time: '00:00',
    description: '11월 ISM 제조업 PMI',
  },
  {
    id: 'kr-cpi-dec-2026',
    date: '2026-12-01',
    title: '한국 CPI 발표',
    category: 'institution',
    countryCode: 'kr',
    importance: 'medium',
    time: '08:00',
    description: '11월 소비자물가지수',
  },
  {
    id: 'us-jobs-dec-2026',
    date: '2026-12-04',
    title: '미국 고용지표 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '11월 비농업고용 및 실업률',
  },
  {
    id: 'us-cpi-dec-2026',
    date: '2026-12-10',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '11월 소비자물가지수',
  },
  {
    id: 'fomc-dec-2026',
    date: '2026-12-16',
    title: 'FOMC 금리결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'us-pce-dec-2026',
    date: '2026-12-23',
    title: '미국 PCE 물가지수',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '11월 개인소비지출 물가지수',
  },

  // ╔════════════════════════════════════════════════════════════════════════════╗
  // ║                            암호화폐 이벤트                                   ║
  // ╚════════════════════════════════════════════════════════════════════════════╝
  {
    id: 'btc-etf-review-2025',
    date: '2025-01-10',
    title: '비트코인 현물 ETF 1주년',
    category: 'crypto',
    companyDomain: 'bitcoin.org',
    importance: 'medium',
    description: '미국 비트코인 현물 ETF 승인 1주년',
  },
  {
    id: 'eth-prague-2025',
    date: '2025-06-15',
    title: '이더리움 Prague 업그레이드',
    category: 'crypto',
    companyDomain: 'ethereum.org',
    importance: 'high',
    description: '이더리움 실행계층 업그레이드 예정',
  },
  {
    id: 'btc-halving-anniversary-2025',
    date: '2025-04-19',
    title: '비트코인 반감기 1주년',
    category: 'crypto',
    companyDomain: 'bitcoin.org',
    importance: 'medium',
    description: '2024년 반감기 이후 1년',
  },
  {
    id: 'eth-osaka-2026',
    date: '2026-03-15',
    title: '이더리움 Osaka 업그레이드',
    category: 'crypto',
    companyDomain: 'ethereum.org',
    importance: 'high',
    description: '이더리움 합의계층 업그레이드 예정',
  },
  {
    id: 'sol-firedancer-2025',
    date: '2025-09-01',
    title: 'Solana Firedancer 메인넷',
    category: 'crypto',
    companyDomain: 'solana.com',
    importance: 'high',
    description: 'Jump Crypto 개발 검증자 클라이언트 출시 예정',
  },
];
