import { CommunityTab, Post, HotPost, DiscussionStock, ActiveUser } from '@/types/community';

export const communityTabs: CommunityTab[] = [
  { id: 'all', label: '전체' },
  { id: 'stock', label: '종목토론' },
  { id: 'strategy', label: '투자전략' },
  { id: 'analysis', label: '시장분석' },
  { id: 'free', label: '자유게시판' },
  { id: 'qna', label: 'Q&A' },
];

export const posts: Post[] = [
  {
    id: 1,
    category: 'stock',
    categoryLabel: '종목토론',
    title: '삼성전자 내년 HBM 생산량 전망 어떻게 보시나요?',
    author: '투자의신',
    createdAt: '10분 전',
    views: 1542,
    likes: 89,
    comments: 47,
    isHot: true,
    stock: { name: '삼성전자', ticker: '005930' },
  },
  {
    id: 2,
    category: 'analysis',
    categoryLabel: '시장분석',
    title: '12월 FOMC 금리 동결 예상, 시장 영향 분석',
    author: '매크로분석가',
    createdAt: '25분 전',
    views: 2103,
    likes: 156,
    comments: 83,
    isHot: true,
  },
  {
    id: 3,
    category: 'stock',
    categoryLabel: '종목토론',
    title: '테슬라 FSD v13 업데이트 소식, 주가 영향은?',
    author: 'TeslaFan',
    createdAt: '42분 전',
    views: 987,
    likes: 62,
    comments: 31,
    isHot: true,
    stock: { name: 'Tesla', ticker: 'TSLA' },
  },
  {
    id: 4,
    category: 'strategy',
    categoryLabel: '투자전략',
    title: '배당주 포트폴리오 구성 팁 공유합니다',
    author: '배당왕',
    createdAt: '1시간 전',
    views: 756,
    likes: 98,
    comments: 24,
    isHot: false,
  },
  {
    id: 5,
    category: 'qna',
    categoryLabel: 'Q&A',
    title: '미국 주식 양도소득세 계산 방법 질문드립니다',
    author: '주린이',
    createdAt: '1시간 전',
    views: 423,
    likes: 12,
    comments: 18,
    isHot: false,
  },
  {
    id: 6,
    category: 'free',
    categoryLabel: '자유게시판',
    title: '올해 수익률 인증합니다 (+47%)',
    author: '성투맨',
    createdAt: '2시간 전',
    views: 3241,
    likes: 234,
    comments: 156,
    isHot: true,
  },
  {
    id: 7,
    category: 'stock',
    categoryLabel: '종목토론',
    title: 'NVIDIA 실적 발표 후 매수 타이밍 논의',
    author: 'AI투자자',
    createdAt: '2시간 전',
    views: 892,
    likes: 45,
    comments: 29,
    isHot: false,
    stock: { name: 'NVIDIA', ticker: 'NVDA' },
  },
  {
    id: 8,
    category: 'analysis',
    categoryLabel: '시장분석',
    title: '원/달러 환율 1,430원 돌파, 수출주 전망',
    author: '환율전문가',
    createdAt: '3시간 전',
    views: 654,
    likes: 38,
    comments: 21,
    isHot: false,
  },
  {
    id: 9,
    category: 'strategy',
    categoryLabel: '투자전략',
    title: '2025년 유망 섹터 TOP 5 정리',
    author: '섹터분석가',
    createdAt: '4시간 전',
    views: 1876,
    likes: 167,
    comments: 72,
    isHot: true,
  },
  {
    id: 10,
    category: 'qna',
    categoryLabel: 'Q&A',
    title: 'ISA 계좌 vs 연금저축 뭐가 더 유리한가요?',
    author: '절세고민',
    createdAt: '5시간 전',
    views: 521,
    likes: 28,
    comments: 34,
    isHot: false,
  },
  {
    id: 11,
    category: 'stock',
    categoryLabel: '종목토론',
    title: '애플 비전프로 2세대 출시 루머, 투자 의견',
    author: '애플덕후',
    createdAt: '5시간 전',
    views: 678,
    likes: 52,
    comments: 38,
    isHot: false,
    stock: { name: 'Apple', ticker: 'AAPL' },
  },
  {
    id: 12,
    category: 'stock',
    categoryLabel: '종목토론',
    title: 'SK하이닉스 HBM3E 양산 소식에 대한 생각',
    author: '반도체러버',
    createdAt: '6시간 전',
    views: 1124,
    likes: 78,
    comments: 45,
    isHot: true,
    stock: { name: 'SK하이닉스', ticker: '000660' },
  },
  {
    id: 13,
    category: 'stock',
    categoryLabel: '종목토론',
    title: '마이크로소프트 Copilot 매출 성장률 분석',
    author: 'MS투자자',
    createdAt: '7시간 전',
    views: 542,
    likes: 34,
    comments: 19,
    isHot: false,
    stock: { name: 'Microsoft', ticker: 'MSFT' },
  },
];

export const hotPosts: HotPost[] = [
  { id: 6, title: '올해 수익률 인증합니다 (+47%)', comments: 156 },
  { id: 2, title: '12월 FOMC 금리 동결 예상, 시장 영향 분석', comments: 83 },
  { id: 9, title: '2025년 유망 섹터 TOP 5 정리', comments: 72 },
  { id: 1, title: '삼성전자 내년 HBM 생산량 전망 어떻게 보시나요?', comments: 47 },
  { id: 5, title: 'ISA 계좌 vs 연금저축 뭐가 더 유리한가요?', comments: 34 },
];

export const discussionStocks: DiscussionStock[] = [
  { name: '삼성전자', ticker: '005930', mentions: 128 },
  { name: '테슬라', ticker: 'TSLA', mentions: 96 },
  { name: 'SK하이닉스', ticker: '000660', mentions: 84 },
  { name: 'NVIDIA', ticker: 'NVDA', mentions: 72 },
  { name: '애플', ticker: 'AAPL', mentions: 58 },
];

export const activeUsers: ActiveUser[] = [
  { name: '투자의신', avatar: '🧙', posts: 24 },
  { name: '매크로분석가', avatar: '📊', posts: 18 },
  { name: '배당왕', avatar: '👑', posts: 15 },
  { name: 'AI투자자', avatar: '🤖', posts: 12 },
  { name: '섹터분석가', avatar: '🔍', posts: 10 },
];

export const CATEGORY_BADGE_COLORS: Record<string, string> = {
  '종목토론': 'bg-blue-100 text-blue-700',
  '투자전략': 'bg-purple-100 text-purple-700',
  '시장분석': 'bg-green-100 text-green-700',
  '자유게시판': 'bg-gray-100 text-gray-700',
  'Q&A': 'bg-orange-100 text-orange-700',
};
